[project]
name = "benchstreet"
version = "1.0.0"
description = "A curated collection of time series prediction models for one shot, long term financial forecasting evaluation."

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]